---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: data-factory-app
spec:
  encryptedData:
    DB_PASS: AgA8IAMzCmOh2JY7oZvYT0G1Cz1536PtUsl7NNow19aLauyHLi0yHgcJKpivH41LEKW1YTmB1DKysHKqQgrnB53AS+1CTHozxJiI+sDKAWT5TcuLwPvSXu1Y0T2eR22IPPnK8OyLKa+1XpTOoxQFRWqpHNBPIBY+Tq3q8EfCfv2pwmX2SHbGePBL1nmAiQLD2gJoo1p/qyS5YJIP+P/ICZdf6Z+VDtER4Pas3OKIS1D1FVwQRvnHp7QduQ34boF3vq9ai1lwDjYEiJvkYsOGa1+6Tp4AUpCVdN4GBIjkAQRItnZeI/PIxtKQ9wv5s8glbfe5J+ZcPy2YyTiFWJB+DMOnhQnF81ZhPjAahZRQiBDSbe6GIARVI0a9J5AoWK/lr5qOAOVYSlLgbc7bYQYvIJcxdouh2BziOGgu1HPJE0nlJRubyIUY36pSmqZgp3xaReV0goRIoUXqLvkr1LPkep/SaIeGA9C9XADlFLzNPutgeMI9fOzpAAjTz964q6Nfq9i6JL7Bk+sGIUR60Jd6zmMpn4LAtG5A6WQ46wgqAJ7xWwTSLSyTaC6meqltgTVesSdtvVnbJ3jqiFC7qKWCrucGUZiGGsyBCyA2NRrycB6HtblwZq1k1yR1fSizXuY7lQBY4lzTdyEfFWmDwCUETeXlUNM7xVQ5RV3VmexAqxE1NI2L0mw7DM09+vm2wUTWjj0WHkNCxhrgIw==
  template:
    metadata:
      name: app-secrets
      namespace: data-factory-app
    type: Opaque
