---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: data-factory-db
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgB7gz23QNXVJUvClg3rTyk1XQqrQB9LI6VIrG0dVdBpDy1avIOGtbYgcayEVOq6zrfhD8I/UeB+UH+tCyPtFBOcr9pF2S6yZlLV7pqCKQeNF7V6pk1PheqB7H0KM1pU7GUMkFkfFooEbVdl/HvnqkqSYAmG7+UK/4TeFSqi6ZMHpsSkjAfaLfjwQe54FiTlr3M7Qdbe+xuEwbjJZggP3Lvka4EcvEpoOO+tFijo7z8jBpgzjCa09BUfug83gwMA0gBEDxA5gPxpi/8xR/31BPkWqYWiqRvtPqObGQTqPhVMN8nhOkFkqXdLdIeU/TcQoN9I52/ZrcEtkLzCYmzv0tL1K7rTQry/9MpRUiI56FU20D1dvlvhGVx3QK6QwW5c3tz16mcsDaZmnLxBMt8pOHtDsENfwQk2HKGpb30wbvLiwqH1rVgfmNNRvPqcx6UPHDkJ7Wfy/uFOForDRmMBWqPZOzFpeEk7A/Ay0NdOzfpa1vY87WQeFGK4acU3n7Rxc/P+pIVgXB9UTHAY2kQFN7RHCCLnHAi2noxxmBMC9k4UVkviUCJ24ZzKu9bD7R6F4p1jgcxP9JxBpxb1O5sCsdnf4b11SbOFXIMspnLN0r205tCWbTIlIx8FayhlgxPeXGIpsvjMzZMCnvl3Fw726m8NV/V/HI2EkzBNnxEXir6HtbRhTW4CHaZz3qczflvrF5hl5cwIIVDnhw==
  template:
    metadata:
      name: postgres-credentials
      namespace: data-factory-db
    type: Opaque
